In [1]:
import pandas as pd
import numpy as np

from pathlib import Path
from tqdm import tqdm

In [2]:
PROJECT_DIR = Path("..")

RAW_DIR = PROJECT_DIR / "data" / "raw"
PROCESSED_DIR = PROJECT_DIR / "data" / "processed"

META_DIR = RAW_DIR / "meta_data"
SMART_DIR = RAW_DIR / "smart_meter_data"
WEATHER_DIR = RAW_DIR / "weather_data"

In [3]:
print("PROJECT :", PROJECT_DIR.resolve())
print("RAW :", RAW_DIR.resolve())

print("META :", META_DIR.exists())
print("SMART :", SMART_DIR.exists())
print("WEATHER :", WEATHER_DIR.exists())
print("PROCESSED :", PROCESSED_DIR.exists())

PROJECT : D:\@SKIRPSI AZHAR\code
RAW : D:\@SKIRPSI AZHAR\code\data\raw
META : True
SMART : True
WEATHER : True
PROCESSED : True

Load Household Terpilih

In [4]:
selected_households = pd.read_csv(
    PROCESSED_DIR /
    "selected_households.csv"
)

selected_households.head()

,Household_ID,Group,Weather_ID,Installation_HasPVSystem,Protocols_Available,Protocols_HasMultipleVisits,Protocols_ReportIDs,MetaData_Available,SmartMeterData_Available_15min,SmartMeterData_Available_Daily,...,start_date,end_date,duration_days,missing_target,zero_ratio,missing_ratio,duration_score,missing_score,zero_score,final_score
0,1137376,treatment,8jB,False,True,False,[166],True,True,True,...,2019-05-20 00:00:00+00:00,2024-02-27 23:45:00+00:00,1744.0,0.0,0.360697,0.0,1.000000,1.0,0.987827,0.997565
1,121728,treatment,Hg,False,True,False,[268],True,True,True,...,2019-11-03 00:00:00+00:00,2024-02-27 23:45:00+00:00,1577.0,0.0,0.122196,0.0,0.878898,1.0,0.995876,0.938624
2,991118,treatment,Hg,False,True,False,[305],True,True,True,...,2019-11-12 00:00:00+00:00,2024-02-27 23:45:00+00:00,1568.0,0.0,0.130956,0.0,0.872371,1.0,0.995580,0.935302
3,971071,treatment,Hg,False,True,False,[267],True,True,True,...,2019-11-14 00:00:00+00:00,2024-02-27 23:45:00+00:00,1566.0,0.0,0.250266,0.0,0.870921,1.0,0.991554,0.933771
4,868122,treatment,Hg,False,True,False,[242],True,True,True,...,2019-11-12 00:00:00+00:00,2024-02-27 23:45:00+00:00,1568.0,0.0,0.565282,0.0,0.872371,1.0,0.980922,0.932370

In [5]:
selected_ids = (
    selected_households[
        "Household_ID"
    ].tolist()
)

print(
    "Jumlah household:",
    len(selected_ids)
)

Jumlah household: 300

Load Metadata

In [6]:
meta_df = pd.read_csv(
    META_DIR /
    "meta_data.csv",
    sep=";"
)

households_df = pd.read_csv(
    META_DIR /
    "households.csv",
    sep=";"
)

In [7]:
print("Metadata :", meta_df.shape)
print("Households :", households_df.shape)

Metadata : (1358, 13)
Households : (1408, 11)

Filter Hanya 300 Household

In [8]:
meta_df = meta_df[
    meta_df["Household_ID"]
    .isin(selected_ids)
]

households_df = households_df[
    households_df["Household_ID"]
    .isin(selected_ids)
]

In [9]:
print(
    "Metadata selected:",
    meta_df.shape
)

print(
    "Households selected:",
    households_df.shape
)

Metadata selected: (300, 13)
Households selected: (300, 11)

Load Smart Meter 300 Household

In [10]:
SMART_15MIN_DIR = (
    SMART_DIR /
    "15min"
)

smart_files = sorted(
    SMART_15MIN_DIR.glob("*.csv")
)

len(smart_files)

1407

In [11]:
for f in smart_files:
    print(f.name)

100101.csv
100105.csv
1001109.csv
1001118.csv
1001121.csv
1001167.csv
1001188.csv
100119.csv
100120.csv
100122.csv
1001228.csv
100167.csv
100211.csv
1006811.csv
1007079.csv
100721.csv
100768.csv
100778.csv
1008075.csv
100847.csv
100871.csv
100888.csv
1008890.csv
1009851.csv
1011001.csv
101101.csv
101102.csv
1011048.csv
101105.csv
1011058.csv
1011091.csv
1011106.csv
1011196.csv
1011223.csv
101574.csv
1015877.csv
101707.csv
101708.csv
101721.csv
1017510.csv
101761.csv
1017710.csv
101776.csv
101797.csv
101800.csv
1018211.csv
101836.csv
101891.csv
101978.csv
1019880.csv
1019970.csv
1020729.csv
1021031.csv
102105.csv
102106.csv
1021061.csv
102109.csv
1021114.csv
1021117.csv
102113.csv
1021178.csv
102119.csv
102120.csv
102299.csv
102310.csv
10266.csv
1027273.csv
102766.csv
102778.csv
1028118.csv
1028411.csv
102857.csv
103100.csv
1031001.csv
103102.csv
103105.csv
103106.csv
1031061.csv
103108.csv
1031097.csv
103115.csv
103119.csv
103120.csv
1031221.csv
103211.csv
103246.csv
1037173.csv
103721.csv
103724.csv
1037311.csv
1037610.csv
103765.csv
103808.csv
1038167.csv
1038174.csv
103834.csv
103991.csv
104012.csv
104104.csv
104105.csv
104110.csv
1041121.csv
1041141.csv
104118.csv
104461.csv
1045107.csv
104546.csv
1046611.csv
104848.csv
1048611.csv
105113.csv
1051138.csv
105117.csv
1051178.csv
105210.csv
105346.csv
105461.csv
1056907.csv
105697.csv
105714.csv
1057211.csv
105768.csv
105771.csv
1057810.csv
105807.csv
105896.csv
105898.csv
105900.csv
1060.csv
106100.csv
1061006.csv
106102.csv
106103.csv
106105.csv
1061088.csv
106109.csv
1061168.csv
106122.csv
1061228.csv
106310.csv
1065698.csv
1066796.csv
106691.csv
1067471.csv
106769.csv
106791.csv
106841.csv
1068781.csv
1068884.csv
1071021.csv
107104.csv
1071058.csv
107108.csv
107112.csv
107114.csv
1071145.csv
1071156.csv
1071191.csv
1071207.csv
107210.csv
1072861.csv
1073767.csv
107377.csv
107461.csv
1075697.csv
1076504.csv
107706.csv
107719.csv
1077199.csv
1077210.csv
107731.csv
107737.csv
1077787.csv
107821.csv
1078861.csv
1079731.csv
107998.csv
108011.csv
108100.csv
1081057.csv
1081779.csv
108210.csv
1084671.csv
108511.csv
1087011.csv
108707.csv
108757.csv
108758.csv
108787.csv
108798.csv
108810.csv
1088228.csv
108846.csv
108849.csv
108852.csv
1088811.csv
108887.csv
1088901.csv
108927.csv
108987.csv
1090081.csv
109073.csv
1091011.csv
109103.csv
109104.csv
109105.csv
109107.csv
109108.csv
109109.csv
109111.csv
109112.csv
109113.csv
109114.csv
109115.csv
1091151.csv
1091198.csv
1091217.csv
109677.csv
109691.csv
109711.csv
109717.csv
1097185.csv
109857.csv
109879.csv
1101068.csv
1101116.csv
110113.csv
110115.csv
1101151.csv
1101186.csv
110119.csv
1101758.csv
1103097.csv
110385.csv
110411.csv
110461.csv
1105791.csv
110611.csv
110651.csv
1106678.csv
110668.csv
1107010.csv
1107179.csv
110731.csv
110750.csv
110766.csv
110806.csv
110810.csv
110877.csv
1108849.csv
110891.csv
110998.csv
111114.csv
111119.csv
1111201.csv
1111228.csv
1113771.csv
111387.csv
1114639.csv
1114677.csv
111580.csv
111610.csv
111651.csv
111710.csv
1117311.csv
111781.csv
111797.csv
1118080.csv
111811.csv
1118111.csv
1118211.csv
111833.csv
111841.csv
1118682.csv
1118887.csv
111901.csv
111907.csv
111972.csv
1119757.csv
1121037.csv
1121049.csv
112105.csv
112106.csv
1121071.csv
112108.csv
1121081.csv
1121096.csv
112110.csv
112112.csv
112113.csv
1121132.csv
112120.csv
112122.csv
1121221.csv
1125799.csv
1126586.csv
112672.csv
1126821.csv
112691.csv
1127111.csv
112796.csv
112807.csv
112810.csv
112845.csv
1128678.csv
1128878.csv
112891.csv
1129912.csv
112996.csv
1131027.csv
113106.csv
1131098.csv
113115.csv
113116.csv
113119.csv
1136611.csv
1136774.csv
1137376.csv
113817.csv
113861.csv
1138999.csv
113971.csv
113987.csv
114104.csv
1141047.csv
114109.csv
1141091.csv
1141141.csv
114117.csv
114118.csv
114119.csv
114346.csv
114481.csv
114671.csv
114677.csv
114721.csv
114732.csv
1147810.csv
114791.csv
114798.csv
114810.csv
114828.csv
1148546.csv
1148611.csv
1148897.csv
114891.csv
1149841.csv
1151001.csv
115103.csv
115106.csv
1151067.csv
1151137.csv
1151157.csv
115116.csv
115117.csv
115119.csv
115120.csv
1154901.csv
115508.csv
1156791.csv
115698.csv
1158410.csv
115846.csv
1158626.csv
115866.csv
1158778.csv
1158812.csv
1159664.csv
115971.csv
116100.csv
1161021.csv
1161057.csv
1161061.csv
1161068.csv
116107.csv
116117.csv
1161191.csv
1161206.csv
116121.csv
116122.csv
116310.csv
116661.csv
1167377.csv
116747.csv
1168069.csv
116847.csv
116858.csv
116861.csv
116977.csv
117010.csv
117101.csv
117102.csv
117105.csv
1171127.csv
117113.csv
1171168.csv
117119.csv
1171197.csv
117481.csv
117657.csv
11769.csv
1177105.csv
117781.csv
1177982.csv
1178890.csv
1178971.csv
1179971.csv
118101.csv
1181060.csv
1181117.csv
118113.csv
118114.csv
118115.csv
118117.csv
118122.csv
1184672.csv
118468.csv
118657.csv
118665.csv
1186910.csv
118708.csv
118711.csv
118721.csv
118810.csv
1189811.csv
118985.csv
1189907.csv
118998.csv
1191021.csv
1191088.csv
119110.csv
1191122.csv
1191127.csv
119117.csv
119118.csv
119122.csv
1191761.csv
1193858.csv
119461.csv
1194677.csv
119498.csv
1194992.csv
119681.csv
119701.csv
1197198.csv
1197401.csv
119771.csv
119781.csv
119788.csv
119816.csv
119878.csv
1199104.csv
120104.csv
1201117.csv
120112.csv
120116.csv
120120.csv
120461.csv
120659.csv
1206911.csv
120701.csv
120706.csv
1207210.csv
120741.csv
1207711.csv
120818.csv
120871.csv
120891.csv
120901.csv
120912.csv
120986.csv
121046.csv
1211017.csv
121103.csv
121109.csv
1211111.csv
1211151.csv
121116.csv
121120.csv
121121.csv
121299.csv
1214111.csv
121681.csv
121697.csv
121701.csv
121728.csv
121767.csv
121778.csv
121798.csv
121808.csv
1218377.csv
121841.csv
121848.csv
121876.csv
121887.csv
122102.csv
1221027.csv
122108.csv
122110.csv
1221108.csv
122117.csv
1223661.csv
122671.csv
1227981.csv
1228011.csv
1228100.csv
1228108.csv
1228211.csv
122841.csv
122850.csv
122881.csv
122887.csv
1228997.csv
122911.csv
128268.csv
1668910.csv
167211.csv
1678757.csv
1691194.csv
173737.csv
173794.csv
182067.csv
182101.csv
188116.csv
190821.csv
210129.csv
2103971.csv
210757.csv
210774.csv
211457.csv
211790.csv
2119808.csv
212111.csv
24611.csv
2701087.csv
2737946.csv
274791.csv
2767178.csv
279461.csv
2794690.csv
2808310.csv
287100.csv
2887690.csv
298120.csv
310610.csv
310781.csv
311110.csv
312074.csv
3699704.csv
3737828.csv
376757.csv
378118.csv
382698.csv
384398.csv
384468.csv
385971.csv
386751.csv
410083.csv
410190.csv
410269.csv
410387.csv
4113691.csv
411389.csv
4115111.csv
411684.csv
411810.csv
4118210.csv
4120571.csv
412211.csv
417510.csv
419075.csv
428987.csv
4461098.csv
446889.csv
4510365.csv
461018.csv
4610233.csv
461031.csv
4610310.csv
461034.csv
4610411.csv
461086.csv
461089.csv
461095.csv
461101.csv
461104.csv
461128.csv
461132.csv
461158.csv
4612011.csv
461218.csv
461222.csv
461226.csv
4614611.csv
461686.csv
463121.csv
4646467.csv
464736.csv
4657676.csv
466627.csv
466710.csv
466866.csv
466870.csv
467071.csv
467072.csv
4675102.csv
467567.csv
4675977.csv
4676816.csv
4678901.csv
4679573.csv
467969.csv
468005.csv
468185.csv
4682731.csv
468312.csv
468467.csv
468475.csv
4685312.csv
468611.csv
468646.csv
468665.csv
468675.csv
468676.csv
468711.csv
468811.csv
468910.csv
468980.csv
469097.csv
469790.csv
469812.csv
4698365.csv
469980.csv
4710670.csv
477661.csv
478111.csv
4788699.csv
479721.csv
481791.csv
4828868.csv
488371.csv
490811.csv
4911611.csv
5011111.csv
508846.csv
5101791.csv
5102111.csv
510910.csv
5109103.csv
511610.csv
511991.csv
512011.csv
5122717.csv
512280.csv
5411784.csv
5586109.csv
5610182.csv
5657284.csv
5661171.csv
566597.csv
566748.csv
567115.csv
5707486.csv
5769106.csv
582662.csv
5831058.csv
5845834.csv
5849911.csv
5858421.csv
589839.csv
598510.csv
610199.csv
610768.csv
610878.csv
610891.csv
6110784.csv
611610.csv
611629.csv
611797.csv
6118658.csv
6121113.csv
621117.csv
6283122.csv
651051.csv
6510689.csv
6511010.csv
6511379.csv
651157.csv
651224.csv
6512274.csv
652122.csv
6531091.csv
654611.csv
65651.csv
6569121.csv
656927.csv
6577811.csv
658116.csv
6584119.csv
658466.csv
658847.csv
6591818.csv
661038.csv
661051.csv
661091.csv
661119.csv
661131.csv
6611384.csv
661221.csv
664610.csv
664701.csv
664874.csv
666761.csv
6667870.csv
667089.csv
667399.csv
667477.csv
667989.csv
6681117.csv
668190.csv
6683113.csv
668446.csv
668668.csv
6687105.csv
6687651.csv
669010.csv
6690866.csv
6697809.csv
671048.csv
671148.csv
671157.csv
671178.csv
671181.csv
671198.csv
671215.csv
671781.csv
672781.csv
672831.csv
6736812.csv
674801.csv
676510.csv
676890.csv
6769114.csv
677172.csv
677179.csv
6771838.csv
6773102.csv
678103.csv
678617.csv
679810.csv
680717.csv
6808461.csv
680861.csv
681008.csv
681039.csv
6810697.csv
6810810.csv
6810910.csv
681103.csv
681108.csv
681177.csv
681179.csv
681201.csv
6816582.csv
683654.csv
684461.csv
684667.csv
686587.csv
6868115.csv
687075.csv
6870806.csv
6873269.csv
687711.csv
687771.csv
687811.csv
688105.csv
688310.csv
688411.csv
6885841.csv
689115.csv
6891687.csv
689878.csv
689973.csv
6901131.csv
6910490.csv
691079.csv
6911148.csv
691151.csv
691171.csv
694611.csv
6946989.csv
696610.csv
696710.csv
6970105.csv
6970113.csv
697046.csv
697221.csv
697280.csv
6975801.csv
697998.csv
6981151.csv
698310.csv
698511.csv
6988111.csv
6988311.csv
698868.csv
698910.csv
698983.csv
699710.csv
699801.csv
700484.csv
700816.csv
700831.csv
701006.csv
701161.csv
701171.csv
701181.csv
7011879.csv
701191.csv
7011912.csv
701226.csv
7046666.csv
7048688.csv
706646.csv
706817.csv
7069107.csv
7069411.csv
707110.csv
707486.csv
707711.csv
707772.csv
708111.csv
708210.csv
708499.csv
7085118.csv
708610.csv
7086681.csv
709911.csv
7099511.csv
7101112.csv
7101116.csv
710210.csv
710297.csv
710311.csv
7104988.csv
710861.csv
711001.csv
711038.csv
711061.csv
7110973.csv
7111010.csv
7111111.csv
7111711.csv
711181.csv
711209.csv
711368.csv
711446.csv
711510.csv
7115691.csv
711910.csv
712718.csv
7146661.csv
716811.csv
716869.csv
716890.csv
717486.csv
7179878.csv
719010.csv
7190105.csv
719120.csv
720106.csv
7210073.csv
721067.csv
721074.csv
721077.csv
7211010.csv
7211189.csv
7211375.csv
7211510.csv
721157.csv
7212284.csv
724690.csv
725101.csv
726510.csv
726810.csv
7268767.csv
726885.csv
727272.csv
727467.csv
727483.csv
727576.csv
727665.csv
727690.csv
727707.csv
728210.csv
728346.csv
728480.csv
7286748.csv
728689.csv
7296899.csv
730976.csv
731021.csv
731027.csv
731058.csv
731148.csv
731172.csv
7311879.csv
731201.csv
731211.csv
732119.csv
734112.csv
736778.csv
7368811.csv
737072.csv
737105.csv
7374981.csv
737969.csv
7382110.csv
738311.csv
738870.csv
7390756.csv
741004.csv
7410610.csv
7410986.csv
7411010.csv
7411491.csv
7411610.csv
7411611.csv
741169.csv
7412010.csv
741222.csv
7437311.csv
743973.csv
746575.csv
746698.csv
746971.csv
747105.csv
747298.csv
7474976.csv
747510.csv
747511.csv
747787.csv
747897.csv
748012.csv
7482109.csv
748773.csv
7510211.csv
751078.csv
751108.csv
7511311.csv
7511880.csv
7511977.csv
754628.csv
755110.csv
7567787.csv
756811.csv
7569701.csv
7571827.csv
757271.csv
757481.csv
7574841.csv
757671.csv
758039.csv
758210.csv
758467.csv
7584888.csv
758512.csv
759711.csv
759747.csv
760117.csv
7610179.csv
7610646.csv
761079.csv
761118.csv
761141.csv
7611412.csv
7612088.csv
761221.csv
7646451.csv
766510.csv
766870.csv
766880.csv
767371.csv
767977.csv
7679818.csv
768078.csv
768113.csv
768116.csv
768498.csv
7686412.csv
7687011.csv
7699120.csv
769968.csv
769978.csv
771031.csv
7710311.csv
771036.csv
771038.csv
7710486.csv
7710511.csv
7710710.csv
771094.csv
771101.csv
771107.csv
7711667.csv
771193.csv
771207.csv
7746610.csv
7747482.csv
7751047.csv
775840.csv
775891.csv
776736.csv
776751.csv
7771161.csv
777384.csv
7778706.csv
777984.csv
778186.csv
778721.csv
779742.csv
7809983.csv
7810010.csv
781007.csv
781008.csv
781011.csv
781067.csv
781099.csv
7811190.csv
7811599.csv
781218.csv
781771.csv
7836781.csv
784611.csv
7846661.csv
785107.csv
7857510.csv
787072.csv
7870998.csv
7873107.csv
7873786.csv
787675.csv
787784.csv
7878467.csv
788488.csv
788786.csv
788846.csv
788912.csv
7890681.csv
789854.csv
7899341.csv
7899997.csv
7906883.csv
7910273.csv
7910410.csv
7910512.csv
7911575.csv
7911610.csv
791196.csv
796869.csv
7968691.csv
797651.csv
7976811.csv
7978677.csv
797976.csv
798116.csv
7984107.csv
7997585.csv
7999741.csv
799976.csv
801001.csv
801031.csv
8010411.csv
801051.csv
801059.csv
801081.csv
8011069.csv
8011310.csv
8011668.csv
801178.csv
801209.csv
801211.csv
804685.csv
8061051.csv
806911.csv
8070101.csv
807356.csv
8079897.csv
8081081.csv
808112.csv
808410.csv
8086103.csv
8087988.csv
810510.csv
811031.csv
811080.csv
811121.csv
811158.csv
8111796.csv
8112146.csv
8116101.csv
811876.csv
811983.csv
812127.csv
812183.csv
814741.csv
815031.csv
815461.csv
816571.csv
816910.csv
817178.csv
817367.csv
8175116.csv
8175708.csv
818111.csv
818882.csv
8190108.csv
819011.csv
8190120.csv
819694.csv
819776.csv
819946.csv
819991.csv
8210485.csv
821076.csv
821088.csv
8211908.csv
8212283.csv
823761.csv
826511.csv
826780.csv
8270738.csv
827127.csv
827183.csv
8272971.csv
827771.csv
827810.csv
8280779.csv
828110.csv
828446.csv
828710.csv
829883.csv
831011.csv
8310587.csv
8311087.csv
831138.csv
831179.csv
8311865.csv
831189.csv
8312167.csv
8351121.csv
8354610.csv
8369469.csv
8369717.csv
836982.csv
837951.csv
8382841.csv
838351.csv
838501.csv
8399121.csv
840777.csv
8410090.csv
8410411.csv
8410565.csv
8410610.csv
841066.csv
841087.csv
841097.csv
8411812.csv
841184.csv
8412079.csv
841211.csv
8412266.csv
845791.csv
8461026.csv
846104.csv
846688.csv
8466897.csv
846767.csv
8469114.csv
847111.csv
8472728.csv
847480.csv
847511.csv
847575.csv
847678.csv
8478885.csv
848310.csv
848510.csv
8486107.csv
848667.csv
8487107.csv
848810.csv
8498411.csv
8498710.csv
850210.csv
851017.csv
851058.csv
851086.csv
851171.csv
8511911.csv
851218.csv
851227.csv
8546677.csv
8566105.csv
856765.csv
856810.csv
857712.csv
858577.csv
859770.csv
859910.csv
8610383.csv
861048.csv
861061.csv
86109.csv
8611006.csv
861116.csv
861151.csv
8611610.csv
8611670.csv
8611772.csv
8612210.csv
8627071.csv
8646105.csv
8646701.csv
8646875.csv
865116.csv
866804.csv
866969.csv
867110.csv
8671139.csv
867211.csv
8673111.csv
867612.csv
8678172.csv
868010.csv
8681127.csv
868122.csv
8682112.csv
868410.csv
869799.csv
869910.csv
8701118.csv
871038.csv
8710527.csv
871061.csv
871212.csv
872117.csv
874821.csv
875110.csv
876107.csv
876122.csv
876511.csv
8766671.csv
876701.csv
876790.csv
877099.csv
877172.csv
8773113.csv
877510.csv
877669.csv
8778168.csv
877881.csv
8781751.csv
878482.csv
8785461.csv
878751.csv
8790869.csv
879894.csv
881001.csv
881020.csv
881022.csv
881037.csv
881048.csv
881108.csv
881126.csv
8811970.csv
881211.csv
881223.csv
882411.csv
884673.csv
8849888.csv
886783.csv
88721.csv
887646.csv
8877761.csv
887788.csv
887911.csv
8882112.csv
8884861.csv
888787.csv
888887.csv
888888.csv
889410.csv
8898468.csv
891001.csv
8910098.csv
891031.csv
891046.csv
8910697.csv
8910784.csv
8910987.csv
8911412.csv
8946986.csv
8966100.csv
896771.csv
8969472.csv
896968.csv
897166.csv
8971777.csv
897237.csv
897276.csv
897410.csv
8976851.csv
897731.csv
898181.csv
8985109.csv
898879.csv
899787.csv
9010312.csv
901037.csv
9011071.csv
9011284.csv
9011578.csv
901166.csv
901187.csv
9011921.csv
901207.csv
906707.csv
9072837.csv
9073879.csv
9074807.csv
9075869.csv
907759.csv
908310.csv
908510.csv
908741.csv
9097118.csv
9097838.csv
9100837.csv
9111107.csv
911510.csv
9115910.csv
912170.csv
9383109.csv
9483106.csv
966771.csv
966791.csv
968749.csv
970807.csv
970979.csv
971044.csv
971071.csv
9710869.csv
9711086.csv
971151.csv
971201.csv
971206.csv
971217.csv
976510.csv
976612.csv
9770887.csv
9776611.csv
977777.csv
978182.csv
978246.csv
978482.csv
978812.csv
978870.csv
981068.csv
9812028.csv
981227.csv
9816877.csv
9831192.csv
984635.csv
984977.csv
986988.csv
9871788.csv
987461.csv
987611.csv
987810.csv
9880798.csv
988311.csv
988456.csv
9889114.csv
9889190.csv
9894115.csv
989768.csv
991051.csv
991071.csv
991118.csv
991119.csv
9911510.csv
991158.csv
991816.csv
993650.csv
995696.csv
996610.csv
996711.csv
9970781.csv
997102.csv
9975101.csv
997610.csv
9980121.csv
9981041.csv
998181.csv
998988.csv

In [12]:
smart_list = []

for file in tqdm(smart_files):

    temp = pd.read_csv(
        file,
        sep=';'
    )

    temp = temp[
        temp['Household_ID']
        .isin(selected_ids)
    ]

    smart_list.append(temp)

100%|██████████| 1407/1407 [01:25<00:00, 16.50it/s]

In [13]:
smart_df = pd.concat(
    smart_list,
    ignore_index=True
)

In [14]:
smart_df.shape

(30735648, 7)

In [15]:
smart_df.head()

,Household_ID,AffectsTimePoint,Group,Timestamp,kWh_received_Total,kWh_received_HeatPump,kWh_received_Other
0,100101,unknown,control,2020-03-08 00:00:00+00:00,0.0,NaN,NaN
1,100101,unknown,control,2020-03-08 00:15:00+00:00,0.0,NaN,NaN
2,100101,unknown,control,2020-03-08 00:30:00+00:00,0.0,NaN,NaN
3,100101,unknown,control,2020-03-08 00:45:00+00:00,0.0,NaN,NaN
4,100101,unknown,control,2020-03-08 01:00:00+00:00,0.0,NaN,NaN

In [16]:
smart_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30735648 entries, 0 to 30735647
Data columns (total 7 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Household_ID           int64
 1   AffectsTimePoint       str
 2   Group                  str
 3   Timestamp              str
 4   kWh_received_Total     float64
 5   kWh_received_HeatPump  float64
 6   kWh_received_Other     float64
dtypes: float64(3), int64(1), str(3)
memory usage: 2.8 GB

In [17]:
smart_df['Timestamp'] = pd.to_datetime(
    smart_df['Timestamp'],
    utc=True
)

In [18]:
smart_df = (
    smart_df
    .sort_values(
        ['Household_ID', 'Timestamp']
    )
    .reset_index(drop=True)
)

In [19]:
smart_df['Household_ID'].nunique()

300

In [20]:
len(smart_df)

30735648

Integrasi Metadata + Household

In [21]:
house_info = (
    households_df
    .merge(
        meta_df,
        on='Household_ID',
        how='left'
    )
)

house_info.shape

(300, 23)

In [23]:
house_info.head()

,Household_ID,Group,Weather_ID,Installation_HasPVSystem,Protocols_Available,Protocols_HasMultipleVisits,Protocols_ReportIDs,MetaData_Available,SmartMeterData_Available_15min,SmartMeterData_Available_Daily,...,Survey_Building_Residents,Survey_HeatPump_Installation_Type,Survey_HeatDistribution_System_FloorHeating,Survey_HeatDistribution_System_Radiator,Survey_DHW_Production_ByHeatPump,Survey_DHW_Production_ByElectricWaterHeater,Survey_DHW_Production_BySolar,Survey_Installation_HasDryer,Survey_Installation_HasFreezer,Survey_Installation_HasElectricVehicle
0,190821,treatment,Hg,True,True,False,[139],True,True,True,...,4.0,air-source,NaN,NaN,NaN,NaN,True,True,False,NaN
1,1137376,treatment,8jB,False,True,False,[166],True,True,True,...,5.0,ground-source,True,False,NaN,True,NaN,True,True,NaN
2,468185,treatment,Hg,False,True,False,[179],True,True,False,...,2.0,ground-source,True,False,True,NaN,NaN,False,True,NaN
3,781007,treatment,Hg,False,True,False,[181],True,True,False,...,2.0,ground-source,True,False,True,NaN,NaN,False,True,NaN
4,114109,treatment,Hg,False,True,False,[186],True,True,False,...,2.0,ground-source,True,False,True,NaN,NaN,True,True,NaN

In [24]:
house_info.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 23 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Household_ID                                 300 non-null    int64
 1   Group                                        300 non-null    str
 2   Weather_ID                                   300 non-null    str
 3   Installation_HasPVSystem                     151 non-null    object
 4   Protocols_Available                          300 non-null    bool
 5   Protocols_HasMultipleVisits                  300 non-null    bool
 6   Protocols_ReportIDs                          96 non-null     str
 7   MetaData_Available                           300 non-null    bool
 8   SmartMeterData_Available_15min               300 non-null    bool
 9   SmartMeterData_Available_Daily               300 non-null    bool
 10  SmartMeterData_Available_Monthly             300 non-null    bool
 11  Survey_Building_Type                         300 non-null    str
 12  Survey_Building_LivingArea                   297 non-null    float64
 13  Survey_Building_Residents                    299 non-null    float64
 14  Survey_HeatPump_Installation_Type            298 non-null    str
 15  Survey_HeatDistribution_System_FloorHeating  272 non-null    object
 16  Survey_HeatDistribution_System_Radiator      272 non-null    object
 17  Survey_DHW_Production_ByHeatPump             195 non-null    object
 18  Survey_DHW_Production_ByElectricWaterHeater  78 non-null     object
 19  Survey_DHW_Production_BySolar                25 non-null     object
 20  Survey_Installation_HasDryer                 299 non-null    object
 21  Survey_Installation_HasFreezer               299 non-null    object
 22  Survey_Installation_HasElectricVehicle       221 non-null    object
dtypes: bool(6), float64(2), int64(1), object(9), str(5)
memory usage: 50.2+ KB

In [25]:
house_info.isnull().sum().sort_values(
    ascending=False
)

Survey_DHW_Production_BySolar                  275
Survey_DHW_Production_ByElectricWaterHeater    222
Protocols_ReportIDs                            204
Installation_HasPVSystem                       149
Survey_DHW_Production_ByHeatPump               105
Survey_Installation_HasElectricVehicle          79
Survey_HeatDistribution_System_Radiator         28
Survey_HeatDistribution_System_FloorHeating     28
Survey_Building_LivingArea                       3
Survey_HeatPump_Installation_Type                2
Survey_Building_Residents                        1
Survey_Installation_HasFreezer                   1
Survey_Installation_HasDryer                     1
Household_ID                                     0
Group                                            0
SmartMeterData_Available_Monthly                 0
SmartMeterData_Available_Daily                   0
SmartMeterData_Available_15min                   0
MetaData_Available                               0
Protocols_HasMultipleVisits                      0
Protocols_Available                              0
Weather_ID                                       0
Survey_Building_Type                             0
dtype: int64

In [26]:
house_info['Household_ID'].duplicated().sum()

0

Integrasi ke Smart Meter

In [27]:
master_df = (
    smart_df
    .merge(
        house_info,
        on='Household_ID',
        how='left'
    )
)

In [28]:
master_df.shape

(30735648, 29)

In [29]:
master_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30735648 entries, 0 to 30735647
Data columns (total 29 columns):
 #   Column                                       Dtype
---  ------                                       -----
 0   Household_ID                                 int64
 1   AffectsTimePoint                             str
 2   Group_x                                      str
 3   Timestamp                                    datetime64[us, UTC]
 4   kWh_received_Total                           float64
 5   kWh_received_HeatPump                        float64
 6   kWh_received_Other                           float64
 7   Group_y                                      str
 8   Weather_ID                                   str
 9   Installation_HasPVSystem                     object
 10  Protocols_Available                          bool
 11  Protocols_HasMultipleVisits                  bool
 12  Protocols_ReportIDs                          str
 13  MetaData_Available                           bool
 14  SmartMeterData_Available_15min               bool
 15  SmartMeterData_Available_Daily               bool
 16  SmartMeterData_Available_Monthly             bool
 17  Survey_Building_Type                         str
 18  Survey_Building_LivingArea                   float64
 19  Survey_Building_Residents                    float64
 20  Survey_HeatPump_Installation_Type            str
 21  Survey_HeatDistribution_System_FloorHeating  object
 22  Survey_HeatDistribution_System_Radiator      object
 23  Survey_DHW_Production_ByHeatPump             object
 24  Survey_DHW_Production_ByElectricWaterHeater  object
 25  Survey_DHW_Production_BySolar                object
 26  Survey_Installation_HasDryer                 object
 27  Survey_Installation_HasFreezer               object
 28  Survey_Installation_HasElectricVehicle       object
dtypes: bool(6), datetime64[us, UTC](1), float64(5), int64(1), object(9), str(7)
memory usage: 6.7+ GB

In [30]:
master_df.isnull().sum().sort_values(
    ascending=False
).head(20)

kWh_received_HeatPump                          30067200
kWh_received_Other                             30065184
Survey_DHW_Production_BySolar                  28076544
Survey_DHW_Production_ByElectricWaterHeater    22865472
Protocols_ReportIDs                            20041728
Installation_HasPVSystem                       14736864
Survey_DHW_Production_ByHeatPump               10705824
Survey_Installation_HasElectricVehicle          8959008
Survey_HeatDistribution_System_Radiator         3495072
Survey_HeatDistribution_System_FloorHeating     3495072
Survey_Building_LivingArea                       291264
Survey_HeatPump_Installation_Type                175200
Survey_Installation_HasDryer                      73728
Survey_Installation_HasFreezer                    73728
Survey_Building_Residents                         73728
kWh_received_Total                                 2208
Survey_Building_Type                                  0
Household_ID                                          0
SmartMeterData_Available_Monthly                      0
SmartMeterData_Available_Daily                        0
dtype: int64

In [31]:
master_df[
    master_df['Survey_Building_Type']
    .isna()
]['Household_ID'].nunique()

0

Integrasi Weather

In [32]:
weather_files = sorted(
    (WEATHER_DIR / "hourly").glob("*.csv")
)

len(weather_files)

8

In [33]:
weather_list = []

for file in weather_files:

    temp = pd.read_csv(
        file,
        sep=';'
    )

    weather_list.append(temp)

weather_df = pd.concat(
    weather_list,
    ignore_index=True
)

In [34]:
weather_df.shape

(362112, 11)

In [35]:
weather_df.head()

,Weather_ID,Timestamp,Temperature_avg_hourly,DewPoint_hourly,Humidity_avg_hourly,Precipitation_total_hourly,Pressure_BarometricHeight_avg_hourly,Pressure_SeaLevelStandardAtmosphere_avg_hourly,Pressure_SeaLevel_avg_hourly,Sunshine_duration_hourly,WindSpeed_hourly
0,8jB,2019-01-01 00:00:00+00:00,4.8,3.7,91.9,0.0,982.4,1033.6,1035.0,0.0,1.1
1,8jB,2019-01-01 01:00:00+00:00,4.5,3.4,93.5,0.0,982.6,1033.8,1035.2,0.0,1.3
2,8jB,2019-01-01 02:00:00+00:00,4.3,3.5,94.8,0.0,982.8,1034.0,1035.5,0.0,0.9
3,8jB,2019-01-01 03:00:00+00:00,4.2,3.4,95.1,0.0,982.5,1033.7,1035.2,0.0,1.7
4,8jB,2019-01-01 04:00:00+00:00,4.2,3.0,93.5,0.0,981.6,1032.7,1034.3,0.0,1.6

In [36]:
weather_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 362112 entries, 0 to 362111
Data columns (total 11 columns):
 #   Column                                          Non-Null Count   Dtype
---  ------                                          --------------   -----
 0   Weather_ID                                      362112 non-null  str
 1   Timestamp                                       362112 non-null  str
 2   Temperature_avg_hourly                          361477 non-null  float64
 3   DewPoint_hourly                                 361338 non-null  float64
 4   Humidity_avg_hourly                             361438 non-null  float64
 5   Precipitation_total_hourly                      360407 non-null  float64
 6   Pressure_BarometricHeight_avg_hourly            226320 non-null  float64
 7   Pressure_SeaLevelStandardAtmosphere_avg_hourly  226320 non-null  float64
 8   Pressure_SeaLevel_avg_hourly                    181056 non-null  float64
 9   Sunshine_duration_hourly                        226305 non-null  float64
 10  WindSpeed_hourly                                360018 non-null  float64
dtypes: float64(9), str(2)
memory usage: 40.3 MB

In [37]:
weather_df['Timestamp'] = pd.to_datetime(
    weather_df['Timestamp'],
    utc=True
)

In [39]:
master_df['Timestamp_hour'] = (
    master_df['Timestamp']
    .dt.floor('h')
)

In [40]:
weather_df['Timestamp_hour'] = (
    weather_df['Timestamp']
)

In [41]:
master_df.to_pickle(
    PROCESSED_DIR /
    "master_before_weather.pkl"
)

optimasi RAM

In [42]:
weather_df.isnull().sum().sort_values(ascending=False)

Pressure_SeaLevel_avg_hourly                      181056
Sunshine_duration_hourly                          135807
Pressure_BarometricHeight_avg_hourly              135792
Pressure_SeaLevelStandardAtmosphere_avg_hourly    135792
WindSpeed_hourly                                    2094
Precipitation_total_hourly                          1705
DewPoint_hourly                                      774
Humidity_avg_hourly                                  674
Temperature_avg_hourly                               635
Weather_ID                                             0
Timestamp                                              0
Timestamp_hour                                         0
dtype: int64

In [43]:
weather_cols = [
    'Weather_ID',
    'Timestamp_hour',
    'Temperature_avg_hourly',
    'Humidity_avg_hourly',
    'Precipitation_total_hourly',
    'WindSpeed_hourly'
]

In [44]:
weather_small = weather_df[
    weather_cols
].copy()

weather_small.shape

(362112, 6)

In [45]:
['Weather_ID', 'Timestamp_hour']

['Weather_ID', 'Timestamp_hour']

In [46]:
weather_small.duplicated(
    subset=['Weather_ID', 'Timestamp_hour']
).sum()

0

merge weather

In [47]:
master_df = master_df.merge(
    weather_small,
    on=['Weather_ID', 'Timestamp_hour'],
    how='left'
)

In [48]:
master_df.shape

(30735648, 34)

In [49]:
master_df[
    [
        'Temperature_avg_hourly',
        'Humidity_avg_hourly',
        'Precipitation_total_hourly',
        'WindSpeed_hourly'
    ]
].isnull().sum()

Temperature_avg_hourly         25672
Humidity_avg_hourly            25672
Precipitation_total_hourly     61492
WindSpeed_hourly              130788
dtype: int64

In [50]:
master_df.to_parquet(
    PROCESSED_DIR /
    'master_dataset.parquet'
)

In [51]:
master_df.to_pickle(
    PROCESSED_DIR /
    'master_dataset.pkl'
)

Kesimpulan Tahap 01 – Data Integration

Pada tahap Data Integration, seluruh sumber data yang relevan berhasil digabungkan menjadi satu dataset utama (master_df) yang siap digunakan untuk proses Exploratory Data Analysis (EDA) dan preprocessing. Integrasi dilakukan secara bertahap dengan menggabungkan data smart meter, metadata rumah tangga, dan data cuaca menggunakan kunci yang sesuai, yaitu Household_ID untuk menghubungkan data rumah tangga dan Weather_ID serta Timestamp_hour untuk menghubungkan data cuaca.

Proses integrasi dimulai dengan pemilihan 300 household terbaik berdasarkan kualitas data, yang mempertimbangkan durasi observasi, tingkat missing value, dan proporsi konsumsi nol. Selanjutnya, data metadata (meta_data.csv) dan data karakteristik rumah tangga (households.csv) difilter agar hanya mencakup 300 household terpilih. Setelah itu, seluruh data smart meter 15-menit dari 300 household digabungkan sehingga menghasilkan 30.735.648 observasi yang merepresentasikan konsumsi energi rumah tangga selama periode pengamatan.

Tahap berikutnya adalah mengintegrasikan informasi karakteristik rumah tangga ke dalam data smart meter melalui Household_ID. Hasil penggabungan menunjukkan bahwa seluruh observasi berhasil memperoleh informasi metadata tanpa menghasilkan duplikasi data. Setelah itu, data cuaca per jam diintegrasikan menggunakan kombinasi Weather_ID dan Timestamp_hour, sehingga setiap observasi konsumsi energi memiliki informasi kondisi lingkungan pada waktu yang sama.

Dataset akhir yang dihasilkan memiliki ukuran:

30.735.648 baris (observasi)
34 kolom (fitur)

yang terdiri atas:

Variabel Smart Meter
konsumsi total listrik,
konsumsi heat pump,
konsumsi peralatan lain,
timestamp,
group.
Variabel Karakteristik Rumah Tangga
tipe bangunan,
luas bangunan,
jumlah penghuni,
jenis heat pump,
sistem distribusi panas,
kepemilikan kendaraan listrik,
dan karakteristik rumah tangga lainnya.
Variabel Cuaca
temperatur,
kelembapan,
curah hujan,
kecepatan angin.

Hasil evaluasi integrasi menunjukkan bahwa variabel cuaca hanya memiliki tingkat missing value yang sangat kecil (kurang dari 0,5% dari total observasi), sehingga tidak menimbulkan masalah serius terhadap kualitas data. Selain itu, proses merge tidak menghasilkan penambahan jumlah baris maupun duplikasi Household_ID, yang menunjukkan bahwa integrasi data telah dilakukan secara konsisten dan valid.

Secara keseluruhan, tahap Data Integration berhasil menghasilkan sebuah master dataset yang terintegrasi, konsisten, dan siap untuk dianalisis lebih lanjut. Dataset ini telah menggabungkan informasi konsumsi energi, karakteristik rumah tangga, dan kondisi cuaca dalam satu struktur data terpadu, sehingga memungkinkan dilakukannya analisis eksploratif yang lebih mendalam pada tahap berikutnya, yaitu 02 – Exploratory Data Analysis (EDA) untuk menentukan strategi preprocessing dan feature engineering yang paling tepat.